version: '3.8'
services:
# simple myself setup
    mysql:
        image: mysql:5.7
        ports:
            - "3307:3306"
        container_name: db-ERP
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ERPFunderectg
            MYSQL_USER: erp
            MYSQL_PASSWORD: erp

# grafana used for graphing mysql data
    grafana:
        image: grafana/grafana-enterprise
        ports:
            - '3500:3000'
        restart: unless-stopped
        container_name: grafana-dashboard
        user: '0'
        environment:
            GF_INSTALL_PLUGINS: percona-percona-app, grafana-clock-panel, grafana-simple-json-datasource
        volumes:
            - grafana-storage:/var/lib/grafana
volumes:
    grafana-storage: {}

# tool to connect to mysql instance, and allow prometheus to collect mysql stats
    # prom_mysql_exporter:
    #     image: prom/mysqld-exporter
    #     links:
    #         - mysql
    #     ports:
    #         - '9104:9104'
    #     environment:
    #         DATA_SOURCE_NAME: root:@(mysql:3306)/adminlte3
    #     command: /bin/mysqld_exporter collect.binlog_size=true collect.info_schema.processlist=true

# prometheus stores and handles timeseries data for statistics around mysql
    # prometheus:
    #     image: prom/prometheus
    #     volumes:
    #         - ./prometheus:/etc/prometheus
    #     links:
    #         - prom_mysql_exporter
    #     ports:
    #         - '9090:9090'
